[versions]
agp = "8.2.0"
kotlin = "1.9.20"
shizuku = "13.1.0"

[libraries]
shizuku-api = { group = "dev.rikka.shizuku", name = "api", version.ref = "shizuku" }
shizuku-provider = { group = "dev.rikka.shizuku", name = "provider", version.ref = "shizuku" }